name = "kagi-earth"
main = "worker.js"
compatibility_date = "2025-08-15"

# Custom domain (optional)
# route = "backgrounds.yourdomain.com/*"

workers_dev = true

[env.production]
name = "kagi-earth"
# route = "backgrounds.yourdomain.com/*"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
